### ISSUE TITLE
Fails to start with dbus-python 1.2.4

### ISSUE THREAD

**Issue by Warudo** [gen2brain/volti#54]
[Issue #53](https://github.com/gen2brain/volti/issues/53) is fixed with dbus-python 1.2.4.
However when you start it with 1.2.4, the error is now:
`ImportError: No module named _version`

I think `import dbus._version` needs to be changed to `from _dbus_bindings import __version__`.

**Comment by gen2brain** [comment]
That check can be removed then. I am not sure what feature I needed that was in >= 0.80 but that was long time ago.

Problem is that current master contains unfinished port to gtk3, pyalsa, etc. It was not branched, and it is imported from googlecode like that. I will first have to sort that out, and then I can also import distro patches, I know there are some.
